[package]
name = "rust-argon2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "0.8"
threadpool = "1.0"
num_cpus = "1.0"

[[bin]]
name = "rust-argon2"
path = "main.rs"
