[package]
name = "rust-argonautica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argonautica = "0.2.0"
threadpool = "1.0"
num_cpus = "1.0"

[[bin]]
name = "rust-argonautica"
path = "main.rs"
